//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PISMS_Service_Realtime.SMSGateway {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMS_Result", Namespace="http://schwebpart:83/")]
    [System.SerializableAttribute()]
    public partial class SMS_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                if ((this.resultField.Equals(value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schwebpart:83/", ConfigurationName="SMSGateway.ICTSMSDTACSoap")]
    public interface ICTSMSDTACSoap {
        
        // CODEGEN: Generating message contract since element name in_msn_list from namespace http://schwebpart:83/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://schwebpart:83/sendSMS2DTAC", ReplyAction="*")]
        PISMS_Service_Realtime.SMSGateway.sendSMS2DTACResponse sendSMS2DTAC(PISMS_Service_Realtime.SMSGateway.sendSMS2DTACRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMS2DTACRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMS2DTAC", Namespace="http://schwebpart:83/", Order=0)]
        public PISMS_Service_Realtime.SMSGateway.sendSMS2DTACRequestBody Body;
        
        public sendSMS2DTACRequest() {
        }
        
        public sendSMS2DTACRequest(PISMS_Service_Realtime.SMSGateway.sendSMS2DTACRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schwebpart:83/")]
    public partial class sendSMS2DTACRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in_msn_list;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in_sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string in_msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public char in_msg_type;
        
        public sendSMS2DTACRequestBody() {
        }
        
        public sendSMS2DTACRequestBody(string in_msn_list, string in_sender, string in_msg, char in_msg_type) {
            this.in_msn_list = in_msn_list;
            this.in_sender = in_sender;
            this.in_msg = in_msg;
            this.in_msg_type = in_msg_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMS2DTACResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMS2DTACResponse", Namespace="http://schwebpart:83/", Order=0)]
        public PISMS_Service_Realtime.SMSGateway.sendSMS2DTACResponseBody Body;
        
        public sendSMS2DTACResponse() {
        }
        
        public sendSMS2DTACResponse(PISMS_Service_Realtime.SMSGateway.sendSMS2DTACResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schwebpart:83/")]
    public partial class sendSMS2DTACResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PISMS_Service_Realtime.SMSGateway.SMS_Result sendSMS2DTACResult;
        
        public sendSMS2DTACResponseBody() {
        }
        
        public sendSMS2DTACResponseBody(PISMS_Service_Realtime.SMSGateway.SMS_Result sendSMS2DTACResult) {
            this.sendSMS2DTACResult = sendSMS2DTACResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICTSMSDTACSoapChannel : PISMS_Service_Realtime.SMSGateway.ICTSMSDTACSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CTSMSDTACSoapClient : System.ServiceModel.ClientBase<PISMS_Service_Realtime.SMSGateway.ICTSMSDTACSoap>, PISMS_Service_Realtime.SMSGateway.ICTSMSDTACSoap {
        
        public CTSMSDTACSoapClient() {
        }
        
        public CTSMSDTACSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CTSMSDTACSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTSMSDTACSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTSMSDTACSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PISMS_Service_Realtime.SMSGateway.sendSMS2DTACResponse PISMS_Service_Realtime.SMSGateway.ICTSMSDTACSoap.sendSMS2DTAC(PISMS_Service_Realtime.SMSGateway.sendSMS2DTACRequest request) {
            return base.Channel.sendSMS2DTAC(request);
        }
        
        public PISMS_Service_Realtime.SMSGateway.SMS_Result sendSMS2DTAC(string in_msn_list, string in_sender, string in_msg, char in_msg_type) {
            PISMS_Service_Realtime.SMSGateway.sendSMS2DTACRequest inValue = new PISMS_Service_Realtime.SMSGateway.sendSMS2DTACRequest();
            inValue.Body = new PISMS_Service_Realtime.SMSGateway.sendSMS2DTACRequestBody();
            inValue.Body.in_msn_list = in_msn_list;
            inValue.Body.in_sender = in_sender;
            inValue.Body.in_msg = in_msg;
            inValue.Body.in_msg_type = in_msg_type;
            PISMS_Service_Realtime.SMSGateway.sendSMS2DTACResponse retVal = ((PISMS_Service_Realtime.SMSGateway.ICTSMSDTACSoap)(this)).sendSMS2DTAC(inValue);
            return retVal.Body.sendSMS2DTACResult;
        }
    }
}
